### ISSUE TITLE
Expose resizing of keyboards to users

### ISSUE THREAD

**Issue by kmcnaught** [SpecialEffect/EyeMine#6]
Several users have now requested resizable keyboards.

**Comment by kmcnaught** [comment]
It might actually be worth re-instating OptiKey's floating option, although it's not ideal (docking works really nicely, since you just maximise minecraft) it does give the flexibility to set size however you like.

**Comment by JuliusSweetland** [comment]
@kmcnaught Perhaps reinstate the move/resize/jump keyboard, but disable or remove the move options to you can't un-dock EyeMine?

**Comment by kmcnaught** [comment]
Superceded by resizing changes
